/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;

/**
 *
 * @author Admin
 */
public class booking extends javax.swing.JFrame {

    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
    }
    public booking(String user){
        initComponents();
        jLabel10.setText(user);
    }
    public booking(String u,String t){
        initComponents();
        jLabel10.setText(u);
        jTextField1.setText(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coimbatore", "Chennai", "Bangalore", "Mumbai" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);

        jLabel7.setText("Time:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coimbatore", "Chennai", "Bangalore", "Mumbai" }));

        jLabel8.setText("Amount:");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("PROCEED TO PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jDateChooser1.setMinSelectableDate(new Date());

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox4.setEnabled(false);

        jLabel6.setText("Type");

        jTextField2.setEditable(false);

        jLabel9.setText("Cost/Tic :");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 Am", "11 pm" }));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Continue");
        jButton2.setDefaultCapable(false);
        jButton2.setEnabled(false);
        jButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButton2ItemStateChanged(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("User Name:");

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Booking Id:");

        jLabel2.setText("NO.of.Tickets:");

        jTextField1.setEditable(false);

        jLabel3.setText("From:");

        jLabel12.setText("Card Number:");

        jLabel4.setText("To:");

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Date:");

        jLabel13.setText("CCV number:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SleeperA/c", "SleeperNonA/c", "semiSleeperA/c", "semiSleeperNonA/c" }));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\project\\booking.png")); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\project\\ticlogoed.png")); // NOI18N

        jLabel15.setText("BUS Id:");

        jTextField6.setEditable(false);

        jButton4.setBackground(new java.awt.Color(255, 153, 255));
        jButton4.setText("Check Availability");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel3)))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton4)
                                            .addComponent(jButton2)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                        .addComponent(jLabel16)
                                        .addGap(56, 56, 56))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int flag=0;
        cancellation c=new cancellation();
        String us;
        int cost,amt;
        int bookingid1;
        us=jLabel10.getText();
        String bo=jTextField1.getText();
        bookingid1=Integer.parseInt(bo);
        Date thisDate=new Date();
        // jDateChooser1.getJCalendar().setMinSelectableDate(new Date());
        SimpleDateFormat sdf=new SimpleDateFormat("MM-dd-yyyy");
        String date=sdf.format(jDateChooser1.getDate());
        String from=(String) jComboBox1.getSelectedItem();
        String to=(String) jComboBox2.getSelectedItem();
        String Ticket=(String) jComboBox4.getSelectedItem();
        String type=(String) jComboBox3.getSelectedItem();
        int busid=Integer.parseInt(jTextField6.getText());
        int t=Integer.parseInt(Ticket);
        String time=(String) jComboBox5.getSelectedItem();
        cost=Integer.parseInt(jTextField2.getText());
        amt=Integer.parseInt(jTextField4.getText());
        long card=Long.parseLong(jTextField3.getText());
        int ccv=Integer.parseInt(jTextField5.getText());
     //   SimpleDateFormat sdf=new SimpleDateFormat("MM-dd-yyyy");
        String journey=sdf.format(jDateChooser1.getDate());
         String timing=(String) jComboBox5.getSelectedItem();
        cancellation.jTextField1.setText(bo);
        int response=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO PROCEED WITH PAYMENT?","CONFIRM",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            //System.out.println("hey");
            try{
               // System.out.println("ooi");
                Connection Con=null;
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Simon1408");
                Statement stmt=Con.createStatement();
                String insert_query="insert into book"+"(bookingid,username,tickets,pick,dropdown,btype,journey,timing,cardno,ccv,busid,cost,total)"
                + "values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
                String sql="insert into log2"+"(busid,pick,dropdown,btype,journey,timing,tickets)"
                        +"values(?,?,?,?,?,?,?)";
                String s="select * from log2 where busid='"+busid+"' and journey='"+journey+"'";
                PreparedStatement preSt=Con.prepareStatement(insert_query);
                PreparedStatement preSt1=Con.prepareStatement(s);
               
                 preSt.setInt(1,bookingid1);
                preSt.setString(2,us);
                preSt.setInt(3,t);
                preSt.setString(4,from);
                preSt.setString(5,to);
                preSt.setString(6,type);
                preSt.setString(7,date);
                preSt.setString(8,time);
                preSt.setLong(9,card);
                preSt.setInt(10,ccv);
                preSt.setInt(11,busid);
                preSt.setInt(12,cost);
                preSt.setInt(13,amt);
                preSt.executeUpdate();
                
               // preSt1.executeUpdate();
                ResultSet rs=preSt1.executeQuery();
              //  System.out.println("hloooooo");
                if(rs.next()==true){
                   // System.out.println("hi");
                    if(rs.getInt("tickets")>20){
                        JOptionPane.showMessageDialog(null,"Seats are Full");
                    }
                    else{
                        //System.out.println("hello");
                        t=t+(rs.getInt("tickets"));
                        String sql2="update log2 set tickets='"+t+"' where busid='"+busid+"' and journey='"+journey+"'"; 
                        PreparedStatement preSt3=Con.prepareStatement(sql2);
                        preSt3.executeUpdate();
                    }
                    
                }
                else{
                   // System.out.println("hiiiii");
                    PreparedStatement preSt2=Con.prepareStatement(sql);
                    preSt2.setInt(1,busid);
                    preSt2.setString(2,from);
                    preSt2.setString(3,to);
                    preSt2.setString(4,type);
                    preSt2.setString(5,journey);
                    preSt2.setString(6,timing);
                    preSt2.setInt(7,t);
                    preSt2.executeUpdate();
                }                
                Con.close();
                JOptionPane.showMessageDialog(null,"BOOKING SUCCESSFUL");
                main ma=new main();
                String u=booking.jLabel10.getText();
                setVisible(false);
                new main(u).setVisible(true);

            }
            catch(Exception e){}}
        else if(response==JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,"BOOKING UNSUCCESSFUL");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButton2ItemStateChanged
        // TODO add your handling code here
    }//GEN-LAST:event_jButton2ItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==jButton2){
            String from=(String) jComboBox1.getSelectedItem();
            String to=(String) jComboBox2.getSelectedItem();
            String Ticket=(String) jComboBox4.getSelectedItem();
            String type=(String) jComboBox3.getSelectedItem();
           
            if(from==to){
                JOptionPane.showMessageDialog(null,"Same Places has Been Selected...");
            }
            if(from=="Coimbatore"&& to=="Chennai" && type=="SleeperA/c" ){
                int x=500;
                int i=100;
                String i1=String.valueOf(i);
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                jTextField6.setText(i1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
            }
            if(from=="Coimbatore"&& to=="Chennai" && type=="SleeperNonA/c" ){
                int x=400;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int i=101;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
            }
            if(from=="Coimbatore"&& to=="Chennai" && type=="semiSleeperA/c" ){
                int x=350;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=102;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Coimbatore"&& to=="Chennai" && type=="semiSleeperNonA/c" ){
                int x=300;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=103;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Coimbatore"&& (to=="Bangalore" || to=="Mumbai") && type=="SleeperA/c" ){
                int x=800;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=104;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Coimbatore"&& (to=="Bangalore" || to=="Mumbai") && type=="SleeperNonA/c" ){
                int x=700;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=105;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Coimbatore"&& (to=="Bangalore" || to=="Mumbai") && type=="semiSleeperA/c" ){
                int x=650;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=106;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Coimbatore"&& (to=="Bangalore" || to=="Mumbai")&& type=="semiSleeperNonA/c" ){
                int x=600;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=107;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Chennai"&& to=="Coimbatore" && type=="SleeperA/c" ){
                int x=900;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=108;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Chennai"&& to=="Coimbatore" && type=="SleeperNonA/c" ){
                int x=800;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=109;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Chennai"&& to=="Coimbatore" && type=="semiSleeperA/c" ){
                int x=850;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                int i=110;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Chennai"&& to=="Coimbatore" && type=="semiSleeperNonA/c" ){
                int x=500;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=111;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Chennai"&& (to=="Bangalore" || to=="Mumbai") && type=="SleeperA/c" ){
                int x=1000;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=112;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Chennai"&& (to=="Bangalore" || to=="Mumbai") && type=="SleeperNonA/c" ){
                int x=800;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=113;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Chennai"&& (to=="Bangalore" || to=="Mumbai") && type=="semiSleeperA/c" ){
                int x=850;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=114;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if(from=="Chennai"&& (to=="Bangalore" || to=="Mumbai")&& type=="semiSleeperNonA/c" ){
                int x=500;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=115;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if((to=="Chennai" || to=="Coimbatore")&& (from=="Bangalore" || from=="Mumbai") && type=="SleeperA/c" ){
                int x=2000;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=116;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if((to=="Chennai" || to=="Coimbatore")&& (from=="Bangalore" || from=="Mumbai") && type=="SleeperNonA/c" ){
                int x=1800;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=117;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if((to=="Chennai"|| to=="Coimbatore")&& (from=="Bangalore" || from=="Mumbai") && type=="semiSleeperA/c" ){
                int x=1850;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=118;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            if((to=="Chennai" || to=="Coimbatore")&& (from=="Bangalore" || from=="Mumbai")&& type=="semiSleeperNonA/c" ){
                int x=1500;
                String x1=String.valueOf(x);
                jTextField2.setText(x1);
                int t=Integer.parseInt(Ticket);
                int tot=x*t;
                jTextField4.setText(String.valueOf(tot));
                 int i=119;
                String i1=String.valueOf(i);
                jTextField6.setText(i1);
            }
            jTextField3.setEditable(true);
            jTextField5.setEditable(true);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
      
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:\
        main ma=new main();
        String user=booking.jLabel10.getText();
        setVisible(false);
        new main(user).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Date thisDate=new Date();
        // jDateChooser1.getJCalendar().setMinSelectableDate(new Date());
        SimpleDateFormat sdf=new SimpleDateFormat("MM-dd-yyyy");
        String journey=sdf.format(jDateChooser1.getDate());
        String from=(String) jComboBox1.getSelectedItem();
        String to=(String) jComboBox2.getSelectedItem();
        String type=(String) jComboBox3.getSelectedItem();
       // int t=Integer.parseInt(Ticket);
        String time=(String) jComboBox5.getSelectedItem();
        try{
               
                
                 int t;
                 
                Connection Con=null;
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Simon1408");
                Statement stmt=Con.createStatement();
                String s="select tickets from log2 where pick='"+from+"' and dropdown='"+to+"' and btype='"+type+"' and journey='"+journey+"' and timing='"+time+"'";                
                String s1="select * from trip where pick='"+from+"' and dropdown='"+to+"' and btype='"+type+"' and journey='"+journey+"' and timing='"+time+"'";
                PreparedStatement preSt1=Con.prepareStatement(s);
                PreparedStatement preSt2=Con.prepareStatement(s1);
                ResultSet rs1=preSt1.executeQuery();
                ResultSet rs2=preSt2.executeQuery();
                //System.out.println("hiii");
                if(rs2.next()){
                if(rs1.next()){
                    t=20-(rs1.getInt("tickets"));                 
                    JOptionPane.showMessageDialog(null,"Available seats are"+t+"....");
                    jComboBox4.setEnabled(true);
                    jButton2.setEnabled(true);
                }
                else{
                    t=20;
                    JOptionPane.showMessageDialog(null,"Available seats are"+t+"....");
                    jComboBox4.setEnabled(true);
                    jButton2.setEnabled(true);
                }
                }
                else{
                    JOptionPane.showMessageDialog(null,"No Buses Available");
                }
                 Con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Fields left Empty");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
