/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;

/**
 *
 * @author Admin
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
    }
    public search(String s){
        initComponents();
        jTextField2.setText(s);
    }
    int S=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Back TO Main");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Search By:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "BookingID", "Username", "Tickets", "Pick", "Drop", "Bustype", "Journey", "Timing", "CardNo", "CCV", "BusId", "Cost", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Enter Search Key:");

        jDateChooser1.setEnabled(false);

        jTextField1.setEditable(false);

        jLabel3.setText("Choose Date:");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BookingId", "Username", "CardNo", "Date" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\project\\search.png")); // NOI18N

        jTextField2.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(111, 111, 111)))
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addComponent(jButton2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        admin ad=new admin();
        String usr=jTextField2.getText();
        setVisible(false);
        new admin(usr).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sr=(String) jComboBox1.getSelectedItem();
        if(sr=="Username"){

            try{

                String user=jTextField1.getText();
                Connection Con1=null;
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Simon1408");
                Statement stmt=Con1.createStatement();
                PreparedStatement st=Con1.prepareStatement("select * from book where username=?");
                st.setString(1,user);
                ResultSet rs=st.executeQuery();
                //if(rs.getString("username").equals(user)){
                    int i=0;
                    while(rs.next()){

                        jTable1.getModel().setValueAt(rs.getInt("bookingId"),i,0);
                        jTable1.getModel().setValueAt(rs.getString("username"),i,1);
                        jTable1.getModel().setValueAt(rs.getInt("tickets"),i,2);
                        jTable1.getModel().setValueAt(rs.getString("pick"),i,3);
                        jTable1.getModel().setValueAt(rs.getString("dropdown"),i,4);
                        jTable1.getModel().setValueAt(rs.getString("btype"),i,5);
                        jTable1.getModel().setValueAt(rs.getString("journey"),i,6);
                        jTable1.getModel().setValueAt(rs.getString("timing"),i,7);
                        jTable1.getModel().setValueAt(rs.getLong("cardno"),i,8);
                        jTable1.getModel().setValueAt(rs.getLong("ccv"),i,9);
                        jTable1.getModel().setValueAt(rs.getInt("Busid"),i,10);
                        jTable1.getModel().setValueAt(rs.getInt("cost"),i,11);
                        jTable1.getModel().setValueAt(rs.getInt("total"),i,12);
                        i++;
                    }

                    Con1.close();
                }catch(Exception e){}
            }
            if(sr=="BookingId"){

                try{
                    int user=Integer.parseInt(jTextField1.getText());
                    Connection Con1=null;
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Simon1408");
                    Statement stmt1=Con1.createStatement();
                    PreparedStatement st1=Con1.prepareStatement("select * from book where bookingId=?");
                    st1.setInt(1,user);
                    ResultSet rs=st1.executeQuery();
                    // if(rs.getString("username").equals(user)){
                        int i=0;
                        while(rs.next()){

                            jTable1.getModel().setValueAt(rs.getInt("bookingId"),i,0);
                            jTable1.getModel().setValueAt(rs.getString("username"),i,1);
                            jTable1.getModel().setValueAt(rs.getInt("tickets"),i,2);
                            jTable1.getModel().setValueAt(rs.getString("pick"),i,3);
                            jTable1.getModel().setValueAt(rs.getString("dropdown"),i,4);
                            jTable1.getModel().setValueAt(rs.getString("btype"),i,5);
                            jTable1.getModel().setValueAt(rs.getString("journey"),i,6);
                            jTable1.getModel().setValueAt(rs.getString("timing"),i,7);
                            jTable1.getModel().setValueAt(rs.getLong("cardno"),i,8);
                            jTable1.getModel().setValueAt(rs.getLong("ccv"),i,9);
                            jTable1.getModel().setValueAt(rs.getInt("Busid"),i,10);
                            jTable1.getModel().setValueAt(rs.getInt("cost"),i,11);
                            jTable1.getModel().setValueAt(rs.getInt("total"),i,12);
                            i++;
                        }

                        Con1.close();
                    }catch(Exception e){}
                }
                if(sr=="CardNo"){

                    try{
                        long user=Long.parseLong(jTextField1.getText());
                        Connection Con1=null;
                        Class.forName("oracle.jdbc.driver.OracleDriver");
                        Con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Simon1408");
                        Statement stmt2=Con1.createStatement();
                        PreparedStatement st2=Con1.prepareStatement("select * from book where cardno=?");
                        st2.setLong(1,user);
                        ResultSet rs=st2.executeQuery();
                        // if(rs.getString("username").equals(user)){
                            int i=0;
                            while(rs.next()){

                                jTable1.getModel().setValueAt(rs.getInt("bookingId"),i,0);
                                jTable1.getModel().setValueAt(rs.getString("username"),i,1);
                                jTable1.getModel().setValueAt(rs.getInt("tickets"),i,2);
                                jTable1.getModel().setValueAt(rs.getString("pick"),i,3);
                                jTable1.getModel().setValueAt(rs.getString("dropdown"),i,4);
                                jTable1.getModel().setValueAt(rs.getString("btype"),i,5);
                                jTable1.getModel().setValueAt(rs.getString("journey"),i,6);
                                jTable1.getModel().setValueAt(rs.getString("timing"),i,7);
                                jTable1.getModel().setValueAt(rs.getLong("cardno"),i,8);
                                jTable1.getModel().setValueAt(rs.getLong("ccv"),i,9);
                                jTable1.getModel().setValueAt(rs.getInt("Busid"),i,10);
                                jTable1.getModel().setValueAt(rs.getInt("cost"),i,11);
                                jTable1.getModel().setValueAt(rs.getInt("total"),i,12);
                                i++;
                            }

                            Con1.close();
                        }catch(Exception e){}
                    }
                    if(sr=="Date"){

                        try{
                            Date thisDate=new Date();
                            java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("MM-dd-yyyy");
                            String date=sdf.format(jDateChooser1.getDate());
                            Connection Con1=null;
                            Class.forName("oracle.jdbc.driver.OracleDriver");
                            Con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Simon1408");
                            Statement stmt3=Con1.createStatement();
                            PreparedStatement st3=Con1.prepareStatement("select * from book where journey=?");
                            st3.setString(1,date);
                            ResultSet rs=st3.executeQuery();
                            // if(rs.getString("username").equals(user)){
                                int i=0;
                                while(rs.next()){

                                    jTable1.getModel().setValueAt(rs.getInt("bookingId"),i,0);
                                    jTable1.getModel().setValueAt(rs.getString("username"),i,1);
                                    jTable1.getModel().setValueAt(rs.getInt("tickets"),i,2);
                                    jTable1.getModel().setValueAt(rs.getString("pick"),i,3);
                                    jTable1.getModel().setValueAt(rs.getString("dropdown"),i,4);
                                    jTable1.getModel().setValueAt(rs.getString("btype"),i,5);
                                    jTable1.getModel().setValueAt(rs.getString("journey"),i,6);
                                    jTable1.getModel().setValueAt(rs.getString("timing"),i,7);
                                    jTable1.getModel().setValueAt(rs.getLong("cardno"),i,8);
                                    jTable1.getModel().setValueAt(rs.getLong("ccv"),i,9);
                                    jTable1.getModel().setValueAt(rs.getInt("Busid"),i,10);
                                    jTable1.getModel().setValueAt(rs.getInt("cost"),i,11);
                                    jTable1.getModel().setValueAt(rs.getInt("total"),i,12);
                                    i++;
                                }

                                Con1.close();
                            }catch(Exception e){}
                        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String sr=(String) jComboBox1.getSelectedItem();
        if(sr=="BookingId"){
            jTextField1.setEditable(true);
            jDateChooser1.setEnabled(false);
        }
        if(sr=="Username"){
            jTextField1.setEditable(true);
            jDateChooser1.setEnabled(false);
        }
        if(sr=="CardNo"){
            jTextField1.setEditable(true);
            jDateChooser1.setEnabled(false);
        }
        if(sr=="Date"){
            jTextField1.setEditable(false);
            jDateChooser1.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
